name: Conda CI
on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        miniforge-version: latest
        # use-mamba: true
        channels: conda-forge

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        conda install -c conda-forge pip

    - name: Install local package and dependencies
      shell: bash -l {0}
      run: |
        pip install .[test]
    
    - name: set up install additional dependencies
      shell: bash -l {0}
      run: |
        sudo apt-get install build-essential
        sudo apt-get install libusb-1.0-0-dev
        sudo apt-get install git-core

    - name: Install additional dependencies
      shell: bash -l {0}
      run: |
        git clone https://github.com/labjack/exodriver.git
        cd exodriver/ $ sudo ./install.sh

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest test/ --cov shield_das --cov-report xml --cov-report term
    
    - name: Upload to codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
